# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3491377235b1ec880888a836a9eb98ca9afacd2c1d622f4008efae65545bfb5352128d646b6ea72d65edf4da3ded50bf1ab4dbde5eef677bbf03ab621576b292

test:
  secret_key_base: f15fb3505e6bac56ed51be670f350315c34c6f9a105c1a7d886ef597b87058265e134f4b3e786975d5fbb7c867023e2a2f91a2b43b59c9ef9320770df16b8df8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
